language: node_js
node_js:
- stable
install:
- npm install
script:
- npm test
after_success:
- npm run coverage
deploy:
  provider: npm
  email: jorge@abraiasoftware.com
  api_key:
    secure: NtmR7e1MZSsLf/C7Iz5gG6KSVuWNzBX0yJEoS218yMJvZpxusYidL9NsV9YfiMjC9d4+5uvQMHEVVNq2OF9vEctzyBq1TLHJ/GddFBPReln8pNpREef8FRuNWhL4vJEFGcEAwKmkyI3Hs85gZsScWgP6Sf9dIWN7s2hINQ83crBlUP9X0CNIgoWBX7fGPBgzvvcJna3g4tGZqNAOsf4XoOLiKako0nhfjwp7Aw+QrUbH1Pg/HlABQm32yS1R5q4oqktiSgQWxQrxDtQTQ1FHYNbTVz/MDXf0k5zAq/CAc6hE2a5JkLemwLcGVC7dDnGxsrUGbIW02vaB+LLOBOVfybelc+q9gZGc8HXiN35hc2yKK55zl0/OcOQxfLquulyMtihlxlATocDkuMSoO3NUXVkyj4RQ/dhv5KDBZf1TO7w+5u1qtx0f5sEmdMl4x8XyEkOwdVPehOiHX1VmK9t/F1wQzFlzoFxYZjBz+UENw9oB0roOelDg5gEh7qG2cUV/QHHpaFzsX5NuIku0rqSJ5Byn88+eZ2NhMVFuY3NSJSMRTvm9o410bXuc0ZBdTN3eDp51wopWoH2nQTUCa+SvNaLOT5/kVnyDzF9BXiE1b6TR/Zn9wBlUh4FXcvgvSgtrU/3IwfokjRzf/xXNQ0HiY+Gy4HyfpJNFzHM1jg+Zp4g=
  on:
    tags: true
    repo: abraia/gulp-abraia
