language: node_js
node_js:
- stable
install:
- npm install
script:
- npm test
after_success:
- npm run coverage
deploy:
  provider: npm
  email: jorge@abraiasoftware.com
  api_key:
    secure: hNekB8aD1QiahDJyNmkQkWCAwvtZvBB3zU7OW1M5gCbBYObcaxpEwfqZWMhDW7WZSx+Lk6Trpa6k8zPAcTCCo7nUxSokQyIMeKU6Ntp3b+Bh6P8uKUHXUC/neYCHPDExFtxCrLT5bbjfpUa6xG9KJe9GGm6R/kWrqg9QBF2gNbbo00IQXMxSgLDjnfeqELdMn+T9on0iHDFfru8McbnixbOK3u9sa+PmXRm4QgT28HvDW7j8bokY7t0P4Ih+kr3PIGzbf9xi7bEHx9n+jURwO1hUmEInZ7cNYDQ+sJkgyDd+dfWo5nvtusr90vhqcrjizPf9i0hC2XdaiPY83N7boyjyMvSOiicUGz+zIhHh3koo3hEDn4d3cZlx8JGZz1K4s441gVL22D933WYMSpghObMRt+09E7c57a5uTwxPvHI96xLQLAMR7dBg5P6hsUryDND4/WvlaUlkVbDresqfUgasIoBqmsVq/ZKbX/Wo/lr/qAau+cA3FPyaqfJX6iqcoWL8XpXof+IUAtIYdkxBgnfVHQpuehUeU7bbooxVnhAWqdPlbe5yR93j+aLYVIWwn6QPbipwLGH8S9hY6+F3OioowYA7HDrPz6oEtjhCRke0GbBFpAYjjolhXUAHoCtwlITQbhOZmpF1V4rkshn8+VUZ6zeZn8X4HfS+A9VQKlo=
  on:
    tags: true
    repo: abraia/gulp-abraia
