language: node_js
node_js:
- stable
install:
- npm install
script:
- npm test
after_success:
- npm run coverage
deploy:
  provider: npm
  email: jorge@abraiasoftware.com
  api_key:
    secure: i/XjoQlFRrV0CMnsXieQXTdNdI0topGjCiIZoA1OORSvgBVqb18+oLyttmUZCtMCYK/jdlLZj/29uQ8ySWH46ok8tch9h/6N7KKePy2ajjCDgEyT6FoNJGCcWUCnjqLfX92IaqHjmtFO3u9ox7mZFmxQcvWa0ux3pmSEDZaiIIF5OZo2GxQnqnF5lAZWIkKwOw9/gA0YDRngYA9U1Hs/ViyhMXzSniwnBY45nHR2BSNAlUTl/Swph5qroXhPrSa987XUZboswTVOFpk6Tr68imB35JC4DCnZGsj8zDCiqN62H21oBwBPBhq7/Y3HUwxlfCGxHzkCJxsB2F50azQo62KNpt1tSRlnPu3Axghl2Z0NnuXYfZOjWyQQRzhdYzTWT2YJUOU1zWn+3ZHCxV1WPad/vViJeh19sCioyWqD4vGja1CNGVWudMaNXcv679Xgv+iDRzWVlpbfla+eAHf+mvVjr6oEnJ6fGAvqscAZmpAH5LvBFXlZ2dbHI09fNKLI3m422vIKLaBpEE7eJrLi8P3IoDaqYyUyIrLHDt7mx3dOv/UYGk1xnkRMf52wcd6DB9/1QDNXFePnPR5x1pP2+ho9TKrC1TUojY61gCx75rQhO4b73/6V3PzQ4PeNKUejII5H0Mnuz2jynIAoTz6/0lh7FMcTpqcHkhLRbpwWMkg=
  on:
    tags: true
    repo: abraia/gulp-abraia
